package kuwg.packetapi.ids.serverbound;

public enum Serverbound_1_7_10 {
    KEEP_ALIVE,
    CHAT_MESSAGE,
    USE_ENTITY,
    PLAYER,
    PLAYER_POSITION,
    PLAYER_LOOK,
    PLAYER_POSITION_AND_LOOK,
    PLAYER_DIGGING,
    PLAYER_BLOCK_PLACEMENT,
    HELD_ITEM_CHANGE,
    ANIMATION,
    ENTITY_ACTION,
    STEER_VEHICLE,
    CLOSE_WINDOW,
    CLICK_WINDOW,
    CONFIRM_TRANSACTION,
    CREATIVE_INVENTORY_ACTION,
    ENCHANT_ITEM,
    UPDATE_SIGN,
    PLAYER_ABILITIES,
    TAB_COMPLETE,
    CLIENT_SETTINGS,
    CLIENT_STATUS,
    PLUGIN_MESSAGE
}
